version: "3.3"
services:
  postgres:
    image: postgres:10.4
    container_name: aineko_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: neverever
      POSTGRES_DB: aineko
    networks:
      - aineko_settings_network
  app:
    build: .
    container_name: aineko_settings
    networks:
      - aineko_settings_network
    environment:
      profile: compose
    ports:
      - "8090:8080"

networks:
  aineko_settings_network:
    driver: bridge
