#spring.boot.enableautoconfiguration: true
environment: default
spring.profiles: default
# logging

logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

logging.level.org.hibernate.SQL: debug


## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aineko?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: postgres
    password: neverever
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #create-drop
    # Because detection is disabled you have to set correct dialect by hand.
    database-plattform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        # Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
        temp.use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Hibernate ddl auto (create, create-drop, validate, update)



---
spring.profiles: docker
name: docker
environment: docker
spring.datasource.url: jdbc:postgresql://aineko_postgres:5432/aineko?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8

---
name: compose
environment: compose
spring:
  profiles: compose
  datasource:
    url: jdbc:postgresql://aineko_postgres:5432/aineko
    username: postgres
    password: neverever
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #create-drop
    # Because detection is disabled you have to set correct dialect by hand.
    database-plattform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        # Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
        temp.use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Hibernate ddl auto (create, create-drop, validate, update)

hibernate.hbm2ddl.auto: update #drop-create

---
spring.profiles: production
name: production
environment: production
spring.datasource.url: jdbc:postgresql://settings_db:5432/aineko